services:
  minimaljira:
    container_name: "MinimalJira"
    build:
      context: ../Backend/
      dockerfile: Dockerfile
    ports:
      - "5226:5226"
    depends_on:
      - database
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5226
      - ConnectionStrings__PostgreSQL=Host=database;Username=admin;Password=23022005;Database=MinimalJiraDb;
      - ConnectionStrings__Redis=redis:6379
  
  database:
    container_name: "database-postgreSQL"
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=MinimalJiraDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=23022005
    volumes:
      - minimalJira-database-volume:/var/lib/postgresql/data
  
  redis:
    container_name: "redis"
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - minimalJira-redis-volume:/data
  
volumes:
  minimalJira-database-volume:
    driver: local
  minimalJira-redis-volume:
    driver: local